name: Deploy to Cloud Run

on:
  push:
    branches: [main]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: 👤Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GOOGLE_CLOUD_SERVICE_ACCOUNT_KEY }}

      - name: ☁️ Setup Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: 🚢 Configure Docker
        run: gcloud auth configure-docker

      - name: ⚙️ Build Docker image
        run: |
          docker build \
            -t gcr.io/simpleboards-app/simpleboard:${{ github.sha }} .

      - name: ⬆️ Upload Docker image to Google Artifact Registry
        run: docker push gcr.io/simpleboards-app/simpleboard:${{ github.sha }}

      - name: 👟 Deploy to Cloud Run
        run: |
          gcloud run deploy simpleboard \
            --image=gcr.io/simpleboards-app/simpleboard:${{ github.sha }} \
            --platform=managed \
            --region=us-central1 \
            --allow-unauthenticated \
            --set-env-vars='^|^FIREBASE_SERVICE_ACCOUNT=${{ secrets.FIREBASE_SERVICE_ACCOUNT }}|PUBLIC_FIREBASE_CONFIG=${{ secrets.FIREBASE_CONFIG }}|PUBLIC_FIREBASE_APP_CHECK_SITE_KEY=${{ secrets.FIREBASE_APP_CHECK_SITE_KEY }}|PUBLIC_POSTHOG_PROJECT_TOKEN=${{ secrets.PUBLIC_POSTHOG_PROJECT_TOKEN }}|PUBLIC_POSTHOG_HOST=${{ secrets.PUBLIC_POSTHOG_HOST }}|POSTHOG_API_KEY=${{ secrets.POSTHOG_API_KEY }}|POSTHOG_HOST=${{ secrets.POSTHOG_HOST }}|POSTHOG_CSP_VERSION=${{ secrets.POSTHOG_CSP_VERSION }}'

      - name: ✅ Success
        run: |
          echo "Deployed successfully!"
